### ISSUE TITLE
Incorrect Version mark on V4.4.0

### ISSUE THREAD

**Issue by God-Dnds** [JamCoreModding/right-click-harvest#76]
On Curseforge the V4.4.0+1.21.1 Fabric (rightclickharvest-fabric-4.4.0+1.21.1.jar) is marked to work on 1.21.1 and 1.21 even though it does not work on 1.21
On 1.21 if the previous version is installed it works fine but curseforge prompts you to update. If you update Fabric will give an error saying the mod is for a different version.

**Comment by Jamalam360** [comment]
Yeah, sorry that's a silly oversight on my part. I'll fix it soon.

**Comment by God-Dnds** [comment]
All good just wanted to make sure it was known!

**Comment by God-Dnds** [comment]
I see you pushed Harvest to 4.4.1 and Jamlib 1.2.2 but 1.21 is still crashing now with both giving an error.

**Comment by Jamalam360** [comment]
Oh, the actual issue is that Fabric API is not updated for 1.21.

I would say either upgrade to 1.21.1 (there is no reason not to, it's just a hotfix to 1.21), or if you really want you can use [dependency overrides](https://fabricmc.net/wiki/tutorial:dependency_overrides) to change the fabric api dependency on jamlib and rightclickharvest

**Comment by God-Dnds** [comment]
Ah I see, that makes sense. If fabric API doesn't end up having a 1.21+106 it may be smart to not mark updates as compatible (or not require above fabric 106 and use 102 for 1.21 since its the newest version for 1.21) so you don't get more reports in the future. 

Also thank you for the knowledge that Dependency overrides are much easier that I expected (ofc something to using sparing and only if necessary)
